import { Inter, Roboto_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./Home/Navbar";
import Footer from "./Footer";
const inter = Inter({ subsets: ["latin"] });
const robotoMono = Roboto_Mono({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] }); // New font variable

export const metadata = {
  title: "Baraa Ecom",
  description: "Generated by create next app",
};

function RootLayout({ children, searchParams }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${robotoMono.className}  ${montserrat.className}`}
      >
        <Navbar searchParams={searchParams} />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
